# Generated by Django 3.2.8 on 2021-12-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movies_title', models.CharField(max_length=700)),
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
    ]
